<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ALEJANDRO.CABELLO.RIOSAUTOMATIZA.CL_a-_d43c9e</name>
   <tag></tag>
   <elementGuidId>43bd7b6e-d4cb-4ab9-bac2-6bcd459da0bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L35366270441690442 > span.a-Icon.icon-down-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='L35366270441690442']/span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;ALEJANDRO.CABELLO.RIOS@AUTOMATIZA.CL&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6380154a-8d4b-4a2f-b5ca-7b39d39b1c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Icon icon-down-arrow</value>
      <webElementGuid>7ae3940c-4ac9-4b29-a76d-e5a188e5e25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa8d7f9c-1f75-4ddc-af8a-5ccff87cdddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L35366270441690442&quot;)/span[@class=&quot;a-Icon icon-down-arrow&quot;]</value>
      <webElementGuid>7372f757-c5d4-46a3-aecf-dfec62211d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='L35366270441690442']/span[4]</value>
      <webElementGuid>c09f2617-f5df-4399-a208-c032dfb0468d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button/span[4]</value>
      <webElementGuid>0203d97d-3e92-4f4d-859c-13bfcdfc0cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
