<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Salir del Fiscalizador</name>
   <tag></tag>
   <elementGuidId>d9d4b3e4-bf6a-4f90-8aa5-f85d7895a360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-Menu-labelContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu_L35366270441690442_1']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=&quot;Salir del Fiscalizador&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>518bbaa3-5617-4b5f-a602-90bda652889d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-labelContainer</value>
      <webElementGuid>43476c68-d736-4445-9ae1-b6495dccddb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salir del Fiscalizador</value>
      <webElementGuid>ca3321e4-b2dc-41e6-a8fa-bc8a7ffc70d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_L35366270441690442_1&quot;)/div[@class=&quot;a-Menu-inner&quot;]/span[@class=&quot;a-Menu-labelContainer&quot;]</value>
      <webElementGuid>23a9b7b0-dfd0-4448-ab04-3d7dd3f040f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu_L35366270441690442_1']/div/span</value>
      <webElementGuid>4a6b51dd-1d7d-426a-a101-d1424fff3e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acerca de...'])[1]/following::span[1]</value>
      <webElementGuid>ec8d3cd4-a561-4709-985c-387b85bec1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='---'])[1]/following::span[1]</value>
      <webElementGuid>23c05c7a-2cde-4bf2-97b6-2cd9eca772b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/div/span</value>
      <webElementGuid>2d818b31-6fc4-4f75-8578-39ac23e17e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Salir del Fiscalizador' or . = 'Salir del Fiscalizador')]</value>
      <webElementGuid>ec4ad7a0-edd4-4d7b-be02-e197be7e7b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
